const assert=require('node:assert/strict');
const {assess,costs,COST_FIELDS,date}=require('../static/insights.js');
const now=new Date('2026-10-09T12:00:00Z');
const empty=assess({sections:{}},now);
assert(empty.checks.every(x=>x.status==='unknown'));
const result=assess({sections:{voertuig:[{wacht_op_keuren:'Ja',tenaamstellen_mogelijk:'Nee',wam_verzekerd:'Nee',export_indicator:'Nee',openstaande_terugroepactie_indicator:'Ja',tellerstandoordeel:'Geen oordeel',vervaldatum_apk:'20261008',datum_eerste_toelating:'20200101',datum_eerste_tenaamstelling_in_nederland:'20210101'}]}},now);
assert.equal(result.checks.filter(x=>x.status==='attention').length,5);
assert.equal(result.checks.find(x=>x.title==='Diefstalcheck').status,'unknown');
assert.equal(result.checks.find(x=>x.title==='Tellerstandoordeel').status,'unknown');
assert.equal(result.checks.find(x=>x.title==='APK').value,'1 dagen verstreken');
assert.equal(date('20260230'),null);assert.equal(date('20261301'),null);
assert.equal(assess({sections:{voertuig:[{vervaldatum_apk:'20261009'}]}},now).checks.find(x=>x.title==='APK').status,'attention');
assert.equal(assess({sections:{voertuig:[{vervaldatum_apk:'20261109'}]}},now).checks.find(x=>x.title==='APK').status,'reported');
const zero=Object.fromEntries(COST_FIELDS.map(k=>[k,0]));zero.years=1;
assert.equal(costs({}).complete,false);assert.equal(costs({...zero,fuel_price:''}).complete,false);
assert.equal(costs({...zero,years:0}).complete,false);assert.equal(costs({...zero,km_year:'Infinity'}).complete,false);
assert.equal(costs({...zero,insurance_month:-1}).complete,false);assert.equal(costs({...zero,resale:1}).complete,false);
assert.equal(costs(zero).per_km,null);
const budget=costs({...zero,km_year:12000,litres_100:'5,5',fuel_price:2,insurance_month:50,tax_quarter:150,maintenance_year:300,tyres_year:180,purchase:10000,resale:4000,years:5});
assert.equal(budget.year,4200);assert.equal(budget.month,350);assert.equal(budget.per_km,0.35);
console.log('Insights: date, unknown status, alerts and cost calculations passed.');
